services:
    davidiq.GuestControl.listener:
        class: davidiq\GuestControl\event\main_listener
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
            - '@user'
            - '@request'
            - '%core.php_ext%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
